import path from 'path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

/**
 * The service worker must NOT ship inside the Capacitor build.
 *
 * Capacitor already serves the app from the local bundle, so a SW adds nothing
 * there — but it does add the classic failure mode: a cached shell surviving an
 * app update, leaving users on stale assets with no way to force a refresh.
 * `npm run cap:sync` sets CAPACITOR_BUILD=1 to switch it off.
 */
const isCapacitorBuild = process.env.CAPACITOR_BUILD === '1'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    ...(isCapacitorBuild
      ? []
      : [
          VitePWA({
            registerType: 'prompt',
            // The manifest is generated by scripts/generate-app-icons.mjs and
            // ships in public/ — do not let the plugin emit a second one.
            manifest: false,
            workbox: {
              // Locales and fonts are part of the shell and must work offline.
              globPatterns: ['**/*.{js,css,html,woff2,png,svg,json}'],
              // The largest chunk is ~1.6MB (react-pdf); the default 2MB cap
              // would silently drop it from the precache.
              maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
              navigateFallbackDenylist: [/^\/api\//, /^\/\.well-known\//],
            },
          }),
        ]),
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  build: {
    reportCompressedSize: false,
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-recharts': ['recharts'],
          // NOTE: '@tiptap/extension-underline' was listed here but is not a
          // dependency — Rollup silently ignored it. Removed.
          'vendor-tiptap': ['@tiptap/react', '@tiptap/starter-kit', '@tiptap/extension-link'],
          'vendor-dnd': ['@dnd-kit/core', '@dnd-kit/sortable', '@dnd-kit/utilities'],
          'vendor-react-pdf': ['@react-pdf/renderer'],
          'vendor-pdfjs': ['pdfjs-dist'],
        },
      },
    },
  },
})
