/**
 * Stripe Price IDs — maps internal plan/module/credit-pack IDs
 * to real Stripe Price IDs.
 *
 * Generated by: node scripts/setup-stripe-products.mjs
 *
 * Each product in Stripe has metadata:
 *   Plans:        { trackbliss_plan: 'pro' | 'enterprise' }
 *   Modules:      { trackbliss_module: '<module_id>' }
 *   Credit Packs: { trackbliss_credits: '<count>', trackbliss_credit_pack: '<pack_id>' }
 *
 * Products also have name_de + description_de in metadata for
 * German translations on the Stripe Checkout page.
 */

import type { BillingPlan, ModuleId } from '@/types/billing';

// ============================================
// PLAN PRICES
// ============================================

export const PLAN_PRICES: Record<
  Exclude<BillingPlan, 'free'>,
  { productId: string; monthlyPriceId: string; yearlyPriceId: string }
> = {
  pro: {
    productId: 'prod_TvgDLzshAxfoCl',
    monthlyPriceId: 'price_1SxoqmG3F2f0Er100x4oGnyv',
    yearlyPriceId: 'price_1SxoqmG3F2f0Er10rRkPwRPv',
  },
  enterprise: {
    productId: 'prod_TvgDR2azJai4u4',
    monthlyPriceId: 'price_1SxoqnG3F2f0Er10VadyvTiC',
    yearlyPriceId: 'price_1SxoqnG3F2f0Er10ri6ZqyOg',
  },
};

// ============================================
// MODULE PRICES
// ============================================

export const MODULE_PRICES: Record<
  ModuleId,
  { productId: string; priceId: string }
> = {
  returns_hub_starter: {
    productId: 'prod_TvgD6MR0IbdzAJ',
    priceId: 'price_1SxoqoG3F2f0Er10UH5feeWe',
  },
  returns_hub_professional: {
    productId: 'prod_TvgDuuV9322Ls2',
    priceId: 'price_1SxoqpG3F2f0Er10gx3JxZ6s',
  },
  returns_hub_business: {
    productId: 'prod_TvgDIVxUAvTcP1',
    priceId: 'price_1SxoqpG3F2f0Er10F6pRjcZw',
  },
  supplier_portal: {
    productId: 'prod_TvgDTLBVHJma66',
    priceId: 'price_1SxoqqG3F2f0Er10fCZaYXoI',
  },
  customer_portal: {
    productId: 'prod_TvgDVqxF8utVgc',
    priceId: 'price_1SxoqqG3F2f0Er10eBSCmdRl',
  },
  custom_domain: {
    productId: 'prod_TvgDLyypedZ6O6',
    priceId: 'price_1SxoqrG3F2f0Er10TDht6nRj',
  },
  warehouse_starter: {
    productId: 'prod_placeholder_wh_starter',
    priceId: 'price_placeholder_wh_starter',
  },
  warehouse_professional: {
    productId: 'prod_placeholder_wh_professional',
    priceId: 'price_placeholder_wh_professional',
  },
  warehouse_business: {
    productId: 'prod_placeholder_wh_business',
    priceId: 'price_placeholder_wh_business',
  },
};

// ============================================
// CREDIT PACK PRICES
// ============================================

export const CREDIT_PACK_PRICES: Record<
  string,
  { productId: string; priceId: string }
> = {
  small: {
    productId: 'prod_TvgDOafMmbU4c9',
    priceId: 'price_1SxoqsG3F2f0Er103x3yZWaJ',
  },
  medium: {
    productId: 'prod_TvgDUcsTOqC4g5',
    priceId: 'price_1SxoqsG3F2f0Er10kUvs9aqA',
  },
  large: {
    productId: 'prod_TvgDrKfCOS7w10',
    priceId: 'price_1SxoqtG3F2f0Er10yVbLgAK5',
  },
};

// ============================================
// HELPER: Get price ID by plan + interval
// ============================================

export function getPlanPriceId(
  plan: BillingPlan,
  interval: 'monthly' | 'yearly',
): string | null {
  if (plan === 'free') return null;
  const prices = PLAN_PRICES[plan];
  return interval === 'yearly' ? prices.yearlyPriceId : prices.monthlyPriceId;
}

export function getModulePriceId(moduleId: ModuleId): string {
  return MODULE_PRICES[moduleId].priceId;
}

export function getCreditPackPriceId(packId: string): string | null {
  return CREDIT_PACK_PRICES[packId]?.priceId ?? null;
}
