/**
 * Stripe Price IDs — maps internal plan/module/credit-pack IDs
 * to real Stripe Price IDs.
 *
 * Generated by: node scripts/setup-stripe-products.mjs
 *
 * Each product in Stripe has metadata:
 *   Plans:        { trackbliss_plan: 'pro' | 'enterprise' }
 *   Modules:      { trackbliss_module: '<module_id>' }
 *   Credit Packs: { trackbliss_credits: '<count>', trackbliss_credit_pack: '<pack_id>' }
 *
 * Products also have name_de + description_de in metadata for
 * German translations on the Stripe Checkout page.
 */

import type { BillingPlan, ModuleId } from '@/types/billing';

// ============================================
// PLAN PRICES
// ============================================

export const PLAN_PRICES: Record<
  Exclude<BillingPlan, 'free'>,
  { productId: string; monthlyPriceId: string; yearlyPriceId: string }
> = {
  pro: {
    productId: 'prod_UgZDMi57cAthKC',
    monthlyPriceId: 'price_1ThC4i9GJBS1rMz1aBG0g5ke',
    yearlyPriceId: 'price_1ThC4i9GJBS1rMz1tWx74ybZ',
  },
  enterprise: {
    productId: 'prod_UgZDK4whamSkYJ',
    monthlyPriceId: 'price_1ThC4j9GJBS1rMz1MrcbbRQ9',
    yearlyPriceId: 'price_1ThC4j9GJBS1rMz1gCFsqTyP',
  },
};

// ============================================
// MODULE PRICES
// ============================================

export const MODULE_PRICES: Record<
  ModuleId,
  { productId: string; priceId: string }
> = {
  returns_hub_starter: {
    productId: 'prod_UgZDBwoc427Wpd',
    priceId: 'price_1ThC4k9GJBS1rMz1E0t69M1L',
  },
  returns_hub_professional: {
    productId: 'prod_UgZD95TM43lhPw',
    priceId: 'price_1ThC4k9GJBS1rMz1A2LJAqEt',
  },
  returns_hub_business: {
    productId: 'prod_UgZDLN8j3vGdne',
    priceId: 'price_1ThC4l9GJBS1rMz1y47ayzYM',
  },
  supplier_portal: {
    productId: 'prod_UgZDaXgDWaOcqY',
    priceId: 'price_1ThC4l9GJBS1rMz13Cq2v7ef',
  },
  customer_portal: {
    productId: 'prod_UgZDlyJL73y9yU',
    priceId: 'price_1ThC4m9GJBS1rMz1fRnUxzg0',
  },
  custom_domain: {
    productId: 'prod_UgZDu7JlgEDjf3',
    priceId: 'price_1ThC4m9GJBS1rMz1IInGn8M0',
  },
  warehouse_starter: {
    productId: 'prod_placeholder_wh_starter',
    priceId: 'price_placeholder_wh_starter',
  },
  warehouse_professional: {
    productId: 'prod_placeholder_wh_professional',
    priceId: 'price_placeholder_wh_professional',
  },
  warehouse_business: {
    productId: 'prod_placeholder_wh_business',
    priceId: 'price_placeholder_wh_business',
  },
  commerce_hub_starter: {
    productId: 'prod_placeholder_ch_starter',
    priceId: 'price_placeholder_ch_starter',
  },
  commerce_hub_professional: {
    productId: 'prod_placeholder_ch_professional',
    priceId: 'price_placeholder_ch_professional',
  },
  commerce_hub_business: {
    productId: 'prod_placeholder_ch_business',
    priceId: 'price_placeholder_ch_business',
  },
  feedback_starter: {
    productId: 'prod_placeholder_feedback_starter',
    priceId: 'price_placeholder_feedback_starter',
  },
  feedback_professional: {
    productId: 'prod_placeholder_feedback_professional',
    priceId: 'price_placeholder_feedback_professional',
  },
  feedback_business: {
    productId: 'prod_placeholder_feedback_business',
    priceId: 'price_placeholder_feedback_business',
  },
};

// ============================================
// CREDIT PACK PRICES
// ============================================

export const CREDIT_PACK_PRICES: Record<
  string,
  { productId: string; priceId: string }
> = {
  small: {
    productId: 'prod_UgZD2Zjyv4b3pB',
    priceId: 'price_1ThC4n9GJBS1rMz11s9rYSRp',
  },
  medium: {
    productId: 'prod_UgZDXYK6TBRQ5v',
    priceId: 'price_1ThC4n9GJBS1rMz1UCruqASu',
  },
  large: {
    productId: 'prod_UgZDHJM9MDaFCl',
    priceId: 'price_1ThC4o9GJBS1rMz125SKXxqb',
  },
};

// ============================================
// HELPER: Get price ID by plan + interval
// ============================================

export function getPlanPriceId(
  plan: BillingPlan,
  interval: 'monthly' | 'yearly',
): string | null {
  if (plan === 'free') return null;
  const prices = PLAN_PRICES[plan];
  return interval === 'yearly' ? prices.yearlyPriceId : prices.monthlyPriceId;
}

export function getModulePriceId(moduleId: ModuleId): string {
  return MODULE_PRICES[moduleId].priceId;
}

export function getCreditPackPriceId(packId: string): string | null {
  return CREDIT_PACK_PRICES[packId]?.priceId ?? null;
}
