/**
 * Datenmigrations-Script für DPP Manager
 *
 * Dieses Script extrahiert alle hardcoded Daten aus den Page-Komponenten
 * und exportiert sie als JSON-Dateien für den Import in NoCodeBackend.
 *
 * Ausführung: npx ts-node scripts/export-data-for-migration.ts
 * Oder mit tsx: npx tsx scripts/export-data-for-migration.ts
 */

import * as fs from 'fs';
import * as path from 'path';

// Output-Verzeichnis
const OUTPUT_DIR = path.join(__dirname, '..', 'data-export');

// Sicherstellen, dass das Ausgabeverzeichnis existiert
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// ============================================
// PRODUKTKATEGORIEN
// ============================================

const productCategories = [
  {
    id: 'electronics',
    name: 'Elektronik & IT',
    icon: '💻',
    description: 'Alle elektronischen Geräte und IT-Equipment',
    regulations: ['CE', 'RoHS', 'WEEE', 'EMV', 'RED'],
    subcategories: [
      'Smartphone', 'Tablet', 'Laptop', 'Desktop-PC', 'Server', 'Monitor', 'TV/Fernseher',
      'Kopfhörer', 'Lautsprecher', 'Soundbar', 'HiFi-Anlage', 'Mikrofon',
      'Drucker', 'Scanner', 'Router', 'Switch', 'NAS-Speicher',
      'Externes Laufwerk', 'USB-Stick', 'Speicherkarte',
      'Webcam', 'Projektor', 'Digitalkamera', 'Videokamera',
      'Spielkonsole', 'Gaming-PC', 'VR-Headset',
      'Smartwatch', 'Fitness-Tracker', 'E-Reader',
      'IoT-Gerät', 'Smart Speaker', 'Smart Display',
      'Drohne', 'E-Scooter', 'E-Bike Display',
    ],
  },
  {
    id: 'household-electronics',
    name: 'Haushaltsgeräte',
    icon: '🏠',
    description: 'Elektrische Haushaltsgeräte (Weiße Ware, Kleingeräte)',
    regulations: ['CE', 'RoHS', 'WEEE', 'Energielabel', 'Ökodesign'],
    subcategories: [
      'Kühlschrank', 'Gefrierschrank', 'Kühl-Gefrier-Kombi',
      'Waschmaschine', 'Trockner', 'Waschtrockner',
      'Geschirrspüler', 'Herd', 'Backofen', 'Mikrowelle',
      'Dunstabzugshaube', 'Induktionskochfeld',
      'Kaffeevollautomat', 'Kaffeemaschine', 'Wasserkocher', 'Toaster',
      'Mixer', 'Küchenmaschine', 'Handmixer', 'Pürierstab',
      'Staubsauger', 'Saugroboter', 'Dampfreiniger',
      'Bügeleisen', 'Dampfbügelstation', 'Nähmaschine',
      'Klimaanlage', 'Ventilator', 'Heizlüfter', 'Luftreiniger',
      'Luftbefeuchter', 'Luftentfeuchter',
      'Haartrockner', 'Glätteisen', 'Lockenstab', 'Haarschneider',
      'Rasierer', 'Epiliergerät', 'Elektrische Zahnbürste',
    ],
  },
  {
    id: 'lighting',
    name: 'Beleuchtung',
    icon: '💡',
    description: 'Leuchtmittel und Leuchten',
    regulations: ['CE', 'RoHS', 'WEEE', 'Energielabel', 'Ökodesign'],
    subcategories: [
      'LED-Lampe E27', 'LED-Lampe E14', 'LED-Lampe GU10', 'LED-Lampe G9',
      'LED-Röhre T8', 'LED-Panel', 'LED-Streifen',
      'Halogenlampe', 'Energiesparlampe',
      'Deckenleuchte', 'Wandleuchte', 'Stehlampe', 'Tischlampe',
      'Pendelleuchte', 'Einbaustrahler', 'Außenleuchte',
      'Smart Lighting', 'Smarte Birne', 'Lichtsteuerung',
      'Notbeleuchtung', 'Fluchtwegleuchte', 'Sicherheitsbeleuchtung',
      'UV-Lampe', 'Infrarotlampe', 'Wachstumslampe',
      'Taschenlampe', 'Stirnlampe', 'Arbeitsleuchte',
    ],
  },
  {
    id: 'textiles',
    name: 'Textilien & Mode',
    icon: '👕',
    description: 'Bekleidung, Schuhe und textile Produkte',
    regulations: ['REACH', 'Textilkennzeichnung', 'ESPR/DPP'],
    subcategories: [
      'T-Shirt', 'Hemd', 'Bluse', 'Pullover', 'Jacke', 'Mantel',
      'Hose', 'Jeans', 'Rock', 'Kleid', 'Anzug',
      'Unterwäsche', 'Socken', 'Strumpfhose',
      'Sportbekleidung', 'Funktionskleidung', 'Outdoor-Bekleidung',
      'Arbeitskleidung', 'Berufskleidung', 'Schutzkleidung',
      'Kinderbekleidung', 'Babybekleidung',
      'Schuhe', 'Sneaker', 'Stiefel', 'Sandalen', 'Sportschuhe',
      'Taschen', 'Rucksäcke', 'Koffer',
      'Gürtel', 'Schals', 'Mützen', 'Handschuhe',
      'Heimtextilien', 'Bettwäsche', 'Handtücher', 'Vorhänge',
      'Teppiche', 'Matten', 'Polsterbezüge',
      'Technische Textilien', 'Geotextilien', 'Agrartextilien',
    ],
  },
  {
    id: 'toys',
    name: 'Spielzeug',
    icon: '🧸',
    description: 'Spielwaren für alle Altersgruppen',
    regulations: ['CE', 'Spielzeugrichtlinie', 'REACH', 'EN 71'],
    subcategories: [
      'Elektronisches Spielzeug', 'Lerncomputer', 'Interaktive Puppen',
      'Ferngesteuertes Auto', 'Drohne (Spielzeug)', 'Roboter',
      'Plüschtiere', 'Stofftiere', 'Puppen',
      'LEGO/Bausteine', 'Konstruktionsspielzeug',
      'Brettspiele', 'Kartenspiele', 'Puzzles',
      'Outdoor-Spielzeug', 'Sandspielzeug', 'Wasserspielzeug',
      'Sportspielzeug', 'Bälle', 'Schaukeln',
      'Musikspielzeug', 'Instrumente (Spielzeug)',
      'Kreativspielzeug', 'Malsets', 'Bastelsets',
      'Lernspielzeug', 'Experimentierkästen', 'MINT-Spielzeug',
      'Baby-Spielzeug', 'Rasseln', 'Beißringe',
      'Spielfahrzeuge', 'Modellautos', 'Eisenbahn',
      'Actionfiguren', 'Sammelfiguren',
      'Kostüme', 'Rollenspiel-Zubehör',
    ],
  },
  {
    id: 'furniture',
    name: 'Möbel & Einrichtung',
    icon: '🛋️',
    description: 'Möbel für Wohn- und Arbeitsbereich',
    regulations: ['REACH', 'Holzhandelsverordnung', 'ESPR/DPP'],
    subcategories: [
      'Sofa', 'Sessel', 'Stuhl', 'Hocker', 'Bank',
      'Esstisch', 'Couchtisch', 'Schreibtisch', 'Beistelltisch',
      'Kleiderschrank', 'Kommode', 'Sideboard', 'Regal', 'Vitrine',
      'Bett', 'Bettgestell', 'Hochbett', 'Kinderbett',
      'Matratze', 'Lattenrost', 'Topper',
      'Küchenmöbel', 'Küchenzeile', 'Arbeitsplatte',
      'Badmöbel', 'Waschtisch', 'Spiegelschrank',
      'Büromöbel', 'Bürostuhl', 'Konferenztisch',
      'Gartenmöbel', 'Loungemöbel', 'Sonnenliege',
      'Kindermöbel', 'Wickelkommode', 'Kinderschreibtisch',
      'Polstermöbel', 'Schlafsofa', 'Recamiere',
    ],
  },
  {
    id: 'cosmetics',
    name: 'Kosmetik & Körperpflege',
    icon: '💄',
    description: 'Kosmetische Produkte und Körperpflegeartikel',
    regulations: ['Kosmetikverordnung (EG) 1223/2009', 'REACH', 'CPNP'],
    subcategories: [
      'Gesichtspflege', 'Tagescreme', 'Nachtcreme', 'Serum',
      'Reinigung', 'Gesichtswasser', 'Peeling', 'Maske',
      'Körperpflege', 'Bodylotion', 'Duschgel', 'Seife',
      'Haarpflege', 'Shampoo', 'Conditioner', 'Haarkur',
      'Styling', 'Haarspray', 'Gel', 'Wachs',
      'Make-up', 'Foundation', 'Concealer', 'Puder',
      'Lippenstift', 'Lipgloss', 'Lipliner',
      'Mascara', 'Eyeliner', 'Lidschatten',
      'Nagellack', 'Nagelpflege',
      'Parfüm', 'Eau de Toilette', 'Deo',
      'Sonnenschutz', 'Selbstbräuner', 'After-Sun',
      'Männerpflege', 'Rasiercreme', 'Aftershave',
      'Babypflege', 'Kinderpflege',
      'Naturkosmetik', 'Biokosmetik',
    ],
  },
  {
    id: 'food-contact',
    name: 'Lebensmittelkontakt',
    icon: '🍽️',
    description: 'Materialien und Gegenstände mit Lebensmittelkontakt',
    regulations: ['VO (EG) 1935/2004', 'VO (EU) 10/2011', 'LFGB'],
    subcategories: [
      'Geschirr', 'Teller', 'Schüssel', 'Tasse',
      'Gläser', 'Weingläser', 'Biergläser',
      'Besteck', 'Messer', 'Gabel', 'Löffel',
      'Kochtöpfe', 'Pfannen', 'Auflaufformen',
      'Küchenutensilien', 'Schneidebretter', 'Kochlöffel',
      'Lebensmittelbehälter', 'Vorratsdosen', 'Frischhaltebox',
      'Trinkflaschen', 'Thermoskannen', 'Isolierbecher',
      'Backformen', 'Muffinformen', 'Kuchenformen',
      'Grillzubehör', 'Grillrost', 'Grillzange',
      'Babyflaschen', 'Schnuller', 'Beikostgeschirr',
      'Einweggeschirr', 'Einwegbesteck',
      'Lebensmittelverpackung', 'Folien', 'Beutel',
      'Küchenmaschinen', 'Mixer', 'Entsafter',
    ],
  },
  {
    id: 'batteries',
    name: 'Batterien & Akkus',
    icon: '🔋',
    description: 'Alle Arten von Batterien und Akkumulatoren',
    regulations: ['EU-Batterieverordnung', 'BattG', 'Digitaler Batteriepass'],
    subcategories: [
      'Gerätebatterie AA', 'Gerätebatterie AAA', 'Gerätebatterie C', 'Gerätebatterie D',
      'Knopfzelle', 'Lithium-Knopfzelle', 'Silberoxid-Knopfzelle',
      '9V-Block', 'Spezialbatterien',
      'Lithium-Ionen-Akku', 'Lithium-Polymer-Akku',
      'NiMH-Akku', 'NiCd-Akku',
      'Powerbank', 'Laptop-Akku', 'Smartphone-Akku',
      'E-Bike-Akku', 'E-Scooter-Akku', 'LMT-Batterie',
      'Starterbatterie (SLI)', 'Motorradbatterie',
      'Industriebatterie', 'USV-Batterie', 'Gabelstapler-Batterie',
      'EV-Batterie', 'Traktionsbatterie',
      'Solarspeicher', 'Heimspeicher',
      'Blei-Säure-Batterie', 'AGM-Batterie', 'Gel-Batterie',
    ],
  },
  {
    id: 'chemicals',
    name: 'Chemikalien & Gemische',
    icon: '🧪',
    description: 'Chemische Stoffe und Zubereitungen',
    regulations: ['REACH', 'CLP', 'Biozidverordnung', 'Detergenzienverordnung'],
    subcategories: [
      'Reinigungsmittel', 'Allzweckreiniger', 'Glasreiniger', 'Badreiniger',
      'Waschmittel', 'Vollwaschmittel', 'Colorwaschmittel', 'Weichspüler',
      'Geschirrspülmittel', 'Handspülmittel', 'Maschinenspülmittel',
      'Farben', 'Wandfarbe', 'Holzfarbe', 'Metallfarbe',
      'Lacke', 'Klarlack', 'Buntlack', 'Holzlasur',
      'Verdünner', 'Lösemittel', 'Pinselreiniger',
      'Klebstoffe', 'Holzleim', 'Sekundenkleber', 'Montagekleber',
      'Dichtstoffe', 'Silikon', 'Acryl', 'PU-Schaum',
      'Öle', 'Motoröl', 'Hydrauliköl', 'Schmieröl',
      'Frostschutzmittel', 'Kühlerfrostschutz',
      'Insektizide', 'Pestizide', 'Herbizide',
      'Düngemittel', 'Pflanzenschutzmittel',
      'Industriechemikalien', 'Säuren', 'Laugen',
    ],
  },
  {
    id: 'medical',
    name: 'Medizinprodukte',
    icon: '🏥',
    description: 'Medizinische Geräte und Hilfsmittel',
    regulations: ['MDR (EU) 2017/745', 'IVDR (EU) 2017/746', 'CE'],
    subcategories: [
      'Klasse I - Nicht-invasiv', 'Verbandmaterial', 'Kompressionsstrümpfe',
      'Klasse I - Steril', 'Einmalhandschuhe steril',
      'Klasse IIa', 'Blutdruckmessgerät', 'Fieberthermometer', 'Hörgerät',
      'Klasse IIb', 'Beatmungsgerät', 'Infusionspumpe', 'Defibrilator',
      'Klasse III', 'Herzschrittmacher', 'Implantate',
      'IVD Klasse A', 'Schwangerschaftstest', 'Urintest',
      'IVD Klasse B', 'Blutzuckermessgerät',
      'IVD Klasse C', 'HIV-Test', 'Hepatitis-Test',
      'IVD Klasse D', 'Blutgruppenbestimmung',
      'Hilfsmittel', 'Rollator', 'Rollstuhl', 'Gehhilfe',
      'Orthopädische Einlagen', 'Bandagen', 'Orthesen',
    ],
  },
  {
    id: 'construction',
    name: 'Bauprodukte',
    icon: '🏗️',
    description: 'Baumaterialien und Bauprodukte',
    regulations: ['Bauproduktenverordnung (EU) 305/2011', 'CE', 'DoP'],
    subcategories: [
      'Dämmstoffe', 'Mineralwolle', 'EPS', 'XPS', 'PUR',
      'Fenster', 'Türen', 'Tore',
      'Bodenbeläge', 'Laminat', 'Parkett', 'Vinyl', 'Fliesen',
      'Sanitärprodukte', 'WC', 'Waschbecken', 'Badewanne', 'Dusche',
      'Heizung', 'Heizkörper', 'Fußbodenheizung', 'Wärmepumpe',
      'Elektroinstallation', 'Steckdosen', 'Schalter', 'Kabel',
      'Rohre', 'Fittings', 'Armaturen',
      'Beton', 'Mörtel', 'Estrich',
      'Ziegel', 'Kalksandstein', 'Porenbeton',
      'Holzwerkstoffe', 'OSB', 'MDF', 'Sperrholz',
      'Dachziegel', 'Dachbahnen', 'Dachdämmung',
      'Fassade', 'Putz', 'WDVS',
    ],
  },
  {
    id: 'machinery',
    name: 'Maschinen & Werkzeuge',
    icon: '🔧',
    description: 'Maschinen und elektrische Werkzeuge',
    regulations: ['Maschinenrichtlinie 2006/42/EG', 'CE', 'Outdoor-Lärm-RL'],
    subcategories: [
      'Bohrmaschine', 'Bohrhammer', 'Schlagbohrmaschine',
      'Winkelschleifer', 'Schwingschleifer', 'Bandschleifer',
      'Kreissäge', 'Stichsäge', 'Kappsäge', 'Kettensäge',
      'Akkuschrauber', 'Schlagschrauber',
      'Kompressor', 'Druckluft-Werkzeug',
      'Schweißgerät', 'Lötstation',
      'Rasenmäher', 'Rasentrimmer', 'Heckenschere',
      'Hochdruckreiniger', 'Nasssauger',
      'Industriemaschine', 'CNC-Maschine', 'Fräse', 'Drehmaschine',
      'Fördertechnik', 'Gabelstapler', 'Hubwagen',
      'Druckluftkompressor', 'Hydraulikpumpe',
      'Messinstrumente', 'Multimeter', 'Oszilloskop',
    ],
  },
  {
    id: 'automotive',
    name: 'Kfz-Teile & Zubehör',
    icon: '🚗',
    description: 'Fahrzeugteile und Autozubehör',
    regulations: ['ECE-Regelungen', 'Typgenehmigung', 'REACH'],
    subcategories: [
      'Reifen', 'Sommerreifen', 'Winterreifen', 'Ganzjahresreifen',
      'Felgen', 'Alufelgen', 'Stahlfelgen',
      'Bremsscheiben', 'Bremsbeläge', 'Bremsflüssigkeit',
      'Ölfilter', 'Luftfilter', 'Kraftstofffilter',
      'Scheinwerfer', 'Rückleuchten', 'Blinker',
      'Auspuff', 'Katalysator', 'Partikelfilter',
      'Batterie', 'Anlasser', 'Lichtmaschine',
      'Kühlerschläuche', 'Keilriemen', 'Zahnriemen',
      'Stoßdämpfer', 'Federn', 'Fahrwerk',
      'Scheibenwischer', 'Scheibenwascher',
      'Innenausstattung', 'Sitzbezüge', 'Fußmatten',
      'Navigation', 'Autoradio', 'Dashcam',
      'Kindersitz', 'Babyschale',
    ],
  },
  {
    id: 'sports',
    name: 'Sport & Freizeit',
    icon: '⚽',
    description: 'Sportgeräte und Freizeitartikel',
    regulations: ['PSA-Verordnung', 'CE', 'EN-Normen'],
    subcategories: [
      'Fahrrad', 'E-Bike', 'Mountainbike', 'Rennrad',
      'Heimtrainer', 'Laufband', 'Crosstrainer', 'Rudergerät',
      'Hanteln', 'Gewichte', 'Kraftstation',
      'Fußball', 'Basketball', 'Volleyball', 'Tennis',
      'Golf', 'Golfschläger', 'Golfbag',
      'Skiausrüstung', 'Ski', 'Skistöcke', 'Skischuhe',
      'Snowboard', 'Snowboardbindung',
      'Schwimmausrüstung', 'Schwimmbrille', 'Neopren',
      'Camping', 'Zelt', 'Schlafsack', 'Isomatte',
      'Wanderausrüstung', 'Wanderschuhe', 'Trekkingstöcke',
      'Angeln', 'Angel', 'Rolle', 'Köder',
      'Reitsport', 'Sattel', 'Reithelm',
      'PSA Sport', 'Helm', 'Protektoren', 'Schienbeinschoner',
    ],
  },
  {
    id: 'baby',
    name: 'Baby & Kleinkind',
    icon: '👶',
    description: 'Babyausstattung und Kleinkindprodukte',
    regulations: ['Spielzeugrichtlinie', 'EN 1888', 'ECE R44/R129', 'REACH'],
    subcategories: [
      'Kinderwagen', 'Buggy', 'Kombikinderwagen', 'Geschwisterwagen',
      'Autositze', 'Babyschale', 'Kindersitz Gruppe 1', 'Kindersitz Gruppe 2/3',
      'Babybetten', 'Stubenwagen', 'Reisebett', 'Beistellbett',
      'Hochstühle', 'Treppenhochstuhl', 'Reisehochstuhl',
      'Babytragen', 'Tragetuch', 'Babytrage', 'Kraxe',
      'Stillzubehör', 'Stillkissen', 'Milchpumpe', 'Stilleinlagen',
      'Babyflaschen', 'Sauger', 'Flaschenwärmer', 'Sterilisator',
      'Windeln', 'Einwegwindeln', 'Stoffwindeln', 'Schwimmwindeln',
      'Babypflege', 'Wickelauflage', 'Badewanne', 'Pflegeprodukte',
      'Babykleidung', 'Strampler', 'Bodies', 'Schlafsäcke',
      'Laufgitter', 'Türschutzgitter', 'Treppenschutzgitter',
      'Babyphone', 'Babykamera', 'Sensormatten',
    ],
  },
  {
    id: 'psa',
    name: 'PSA - Schutzausrüstung',
    icon: '🦺',
    description: 'Persönliche Schutzausrüstung',
    regulations: ['PSA-Verordnung (EU) 2016/425', 'CE', 'Kategorie I-III'],
    subcategories: [
      'Kopfschutz', 'Schutzhelm', 'Anstoßkappe', 'Haarschutz',
      'Augenschutz', 'Schutzbrille', 'Vollsichtbrille', 'Gesichtsschild',
      'Gehörschutz', 'Ohrstöpsel', 'Kapselgehörschutz', 'Bügelgehörschutz',
      'Atemschutz', 'FFP-Masken', 'Halbmasken', 'Vollmasken', 'Gebläseatemschutz',
      'Handschutz', 'Arbeitshandschuhe', 'Chemikalienschutz', 'Schnittschutz',
      'Fußschutz', 'Sicherheitsschuhe S1-S3', 'Gummistiefel', 'Überschuhe',
      'Körperschutz', 'Warnweste', 'Schweißerschutz', 'Hitzeschutz',
      'Fallschutz', 'Auffanggurt', 'Sicherheitsseil', 'Höhensicherung',
      'Knieschutz', 'Knieschoner', 'Kniematte',
      'Arbeitskleidung', 'Bundhose', 'Latzhose', 'Arbeitsjacke',
      'Einwegschutz', 'Einwegoverall', 'Einweghandschuhe', 'Überzieher',
    ],
  },
  {
    id: 'renewable',
    name: 'Erneuerbare Energien',
    icon: '☀️',
    description: 'Solar, Wind und Energiespeicher',
    regulations: ['CE', 'Niederspannungsrichtlinie', 'EMV', 'Ökodesign'],
    subcategories: [
      'Solarmodule', 'Monokristallin', 'Polykristallin', 'Dünnschicht',
      'Wechselrichter', 'String-Wechselrichter', 'Hybrid-Wechselrichter', 'Mikro-Wechselrichter',
      'Batteriespeicher', 'Lithium-Speicher', 'Blei-Speicher', 'Salzwasser-Speicher',
      'Montagesysteme', 'Aufdach', 'Indach', 'Flachdach', 'Freifläche',
      'Balkonkraftwerk', 'Stecker-Solar', 'Mini-PV',
      'Solarthermie', 'Flachkollektoren', 'Röhrenkollektoren',
      'Kleinwindanlagen', 'Vertikalachser', 'Horizontalachser',
      'Energiemanagement', 'Smart Meter', 'Energiemonitor', 'Lastmanagement',
      'Wallbox', 'AC-Wallbox', 'DC-Schnelllader', 'Mobile Ladestation',
      'Kabel & Zubehör', 'Solarkabel', 'Stecker', 'Überspannungsschutz',
    ],
  },
];

// ============================================
// LÄNDER
// ============================================

const countries = [
  {
    code: 'DE',
    name: 'Deutschland',
    flag: '🇩🇪',
    regulations: 24,
    checklists: 8,
    authorities: ['BAuA', 'UBA', 'BfR', 'stiftung ear'],
    description: 'Umfangreiche nationale Umsetzungen der EU-Richtlinien mit zusätzlichen Anforderungen',
  },
  {
    code: 'FR',
    name: 'Frankreich',
    flag: '🇫🇷',
    regulations: 18,
    checklists: 7,
    authorities: ['ADEME', 'DGCCRF', 'ANSM'],
    description: 'Vorreiter bei Reparierbarkeit und Anti-Obsoleszenz-Gesetzgebung',
  },
  {
    code: 'AT',
    name: 'Österreich',
    flag: '🇦🇹',
    regulations: 14,
    checklists: 5,
    authorities: ['BMK', 'AGES', 'Umweltbundesamt'],
    description: 'Strenge Umweltauflagen und Verpackungsverordnung',
  },
  {
    code: 'IT',
    name: 'Italien',
    flag: '🇮🇹',
    regulations: 16,
    checklists: 6,
    authorities: ['ISPRA', 'CONAI', 'Ministero della Salute'],
    description: 'Besondere Anforderungen an Produktkennzeichnung und Verpackung',
  },
  {
    code: 'ES',
    name: 'Spanien',
    flag: '🇪🇸',
    regulations: 12,
    checklists: 5,
    authorities: ['MITECO', 'AEMPS', 'CNMC'],
    description: 'Nationale Umsetzung mit Fokus auf Kreislaufwirtschaft',
  },
  {
    code: 'NL',
    name: 'Niederlande',
    flag: '🇳🇱',
    regulations: 15,
    checklists: 6,
    authorities: ['RVO', 'NVWA', 'ILT'],
    description: 'Progressive Umweltpolitik und Kreislaufwirtschaftsstrategie',
  },
  {
    code: 'BE',
    name: 'Belgien',
    flag: '🇧🇪',
    regulations: 13,
    checklists: 5,
    authorities: ['FOD', 'OVAM', 'Bruxelles Environnement'],
    description: 'Regionale Unterschiede bei Umweltauflagen (Flandern, Wallonien, Brüssel)',
  },
  {
    code: 'PL',
    name: 'Polen',
    flag: '🇵🇱',
    regulations: 11,
    checklists: 4,
    authorities: ['GIOŚ', 'UOKiK', 'GIS'],
    description: 'Wachsender Fokus auf EU-Konformität und EPR-Systeme',
  },
  {
    code: 'SE',
    name: 'Schweden',
    flag: '🇸🇪',
    regulations: 16,
    checklists: 6,
    authorities: ['Naturvårdsverket', 'Kemikalieinspektionen'],
    description: 'Strenge Chemikalienverordnung und Nachhaltigkeitsanforderungen',
  },
  {
    code: 'DK',
    name: 'Dänemark',
    flag: '🇩🇰',
    regulations: 14,
    checklists: 5,
    authorities: ['Miljøstyrelsen', 'Sikkerhedsstyrelsen'],
    description: 'Vorreiter bei Kreislaufwirtschaft und Ressourceneffizienz',
  },
  {
    code: 'CZ',
    name: 'Tschechien',
    flag: '🇨🇿',
    regulations: 10,
    checklists: 4,
    authorities: ['MŽP', 'ČIŽP', 'ČOI'],
    description: 'Nationale EPR-Systeme und Verpackungsanforderungen',
  },
  {
    code: 'PT',
    name: 'Portugal',
    flag: '🇵🇹',
    regulations: 11,
    checklists: 4,
    authorities: ['APA', 'ASAE', 'Infarmed'],
    description: 'Fokus auf maritime Nachhaltigkeit und Verpackungsrecycling',
  },
];

// ============================================
// EU-REGULIERUNGEN
// ============================================

const euRegulations = [
  {
    id: 'espr',
    name: 'ESPR (Ecodesign for Sustainable Products Regulation)',
    fullName: 'Verordnung (EU) 2024/1781 über Ökodesign-Anforderungen für nachhaltige Produkte',
    description: 'Rahmenverordnung für nachhaltige Produkte. Führt den Digitalen Produktpass (DPP) ein und erweitert die Ökodesign-Anforderungen auf nahezu alle Produktkategorien.',
    category: 'environment',
    status: 'active',
    effectiveDate: '2024-07-18',
    applicationDate: '2027-01-01',
    keyRequirements: [
      'Digitaler Produktpass (DPP) für alle regulierten Produkte',
      'QR-Code mit Verlinkung zu Produktinformationen',
      'Datenträger mit eindeutiger Produkt-ID',
      'Reparierbarkeit und Langlebigkeit',
      'Recycelte Materialien',
      'Kohlenstoff- und Umweltfußabdruck',
    ],
    affectedProducts: ['Textilien', 'Möbel', 'Reifen', 'Waschmittel', 'Farben', 'Schmierstoffe', 'Chemikalien', 'Elektronik', 'ICT-Produkte', 'Eisen & Stahl'],
    dppDeadlines: {
      'Batterien': '2027-02-18',
      'Textilien': '2027-12-31',
      'Elektronik': '2028-12-31',
      'Möbel': '2029-06-30',
    },
  },
  {
    id: 'battery-regulation',
    name: 'EU-Batterieverordnung',
    fullName: 'Verordnung (EU) 2023/1542 über Batterien und Altbatterien',
    description: 'Umfassende Regelung für den gesamten Lebenszyklus von Batterien. Erster verbindlicher DPP ab Februar 2027.',
    category: 'environment',
    status: 'upcoming',
    effectiveDate: '2023-08-17',
    applicationDate: '2027-02-18',
    keyRequirements: [
      'Digitaler Produktpass mit QR-Code',
      'Mindestgehalt an recyceltem Material (Kobalt, Blei, Lithium, Nickel)',
      'Kohlenstoff-Fußabdruck-Erklärung',
      'Leistungs- und Haltbarkeitsanforderungen',
      'Kennzeichnung und Etikettierung',
      'Due Diligence in der Lieferkette',
      'Sammlung und Recycling',
    ],
    affectedProducts: ['LMT-Batterien', 'Industriebatterien', 'EV-Batterien', 'SLI-Batterien', 'Gerätebatterien'],
    dppDeadlines: {
      'LMT-Batterien >2kWh': '2027-02-18',
      'Industriebatterien >2kWh': '2027-02-18',
      'EV-Batterien': '2027-02-18',
      'Alle anderen': '2028-08-18',
    },
  },
  {
    id: 'reach',
    name: 'REACH-Verordnung',
    fullName: 'Verordnung (EG) Nr. 1907/2006 zur Registrierung, Bewertung, Zulassung und Beschränkung chemischer Stoffe',
    description: 'Zentrales Regelwerk für Chemikalien in der EU. Registrierungspflicht, SVHC-Kandidatenliste, Beschränkungen.',
    category: 'chemicals',
    status: 'active',
    effectiveDate: '2007-06-01',
    applicationDate: '2007-06-01',
    keyRequirements: [
      'Registrierung aller Stoffe >1t/Jahr bei ECHA',
      'Sicherheitsdatenblätter für gefährliche Stoffe',
      'SVHC-Mitteilungspflicht >0,1% w/w',
      'SCIP-Datenbank-Meldung für Erzeugnisse mit SVHCs',
      'Beschränkungen für bestimmte Stoffe (Anhang XVII)',
      'Zulassungspflicht für SVHCs (Anhang XIV)',
    ],
    affectedProducts: ['Alle Produkte mit chemischen Stoffen'],
    dppDeadlines: {},
  },
  {
    id: 'rohs',
    name: 'RoHS-Richtlinie',
    fullName: 'Richtlinie 2011/65/EU zur Beschränkung der Verwendung bestimmter gefährlicher Stoffe in Elektro- und Elektronikgeräten',
    description: 'Beschränkt die Verwendung von 10 gefährlichen Stoffen in Elektrogeräten: Blei, Quecksilber, Cadmium, Chrom VI, PBB, PBDE, DEHP, BBP, DBP, DIBP.',
    category: 'chemicals',
    status: 'active',
    effectiveDate: '2011-07-01',
    applicationDate: '2013-01-03',
    keyRequirements: [
      'Grenzwerte für gefährliche Stoffe einhalten',
      'EU-Konformitätserklärung erstellen',
      'CE-Kennzeichnung anbringen',
      'Technische Dokumentation führen',
      'Ausnahmen prüfen und dokumentieren',
    ],
    affectedProducts: ['Alle Elektro- und Elektronikgeräte (11 Kategorien)'],
    dppDeadlines: {},
  },
  {
    id: 'weee',
    name: 'WEEE-Richtlinie',
    fullName: 'Richtlinie 2012/19/EU über Elektro- und Elektronik-Altgeräte',
    description: 'Regelt die Sammlung, Behandlung und Verwertung von Elektroaltgeräten. Herstellerverantwortung und Sammelziele.',
    category: 'recycling',
    status: 'active',
    effectiveDate: '2012-08-13',
    applicationDate: '2014-02-14',
    keyRequirements: [
      'Registrierung als Hersteller im jeweiligen Mitgliedstaat',
      'Finanzierung der Sammlung und Entsorgung',
      'WEEE-Symbol auf Produkten anbringen',
      'Sammelziele erreichen (65% oder 85% Verwertung)',
      'Mengenmeldungen an Behörden',
    ],
    affectedProducts: ['6 Kategorien von Elektrogeräten'],
    dppDeadlines: {},
  },
  {
    id: 'ce-marking',
    name: 'CE-Kennzeichnung',
    fullName: 'Verordnung (EG) Nr. 765/2008 und Beschluss Nr. 768/2008/EG',
    description: 'Zeigt Konformität mit EU-Harmonisierungsvorschriften an. Voraussetzung für den freien Warenverkehr im Binnenmarkt.',
    category: 'safety',
    status: 'active',
    effectiveDate: '2010-01-01',
    applicationDate: '2010-01-01',
    keyRequirements: [
      'Konformitätsbewertung durchführen',
      'Technische Dokumentation erstellen',
      'EU-Konformitätserklärung ausstellen',
      'CE-Zeichen anbringen (mind. 5mm Höhe)',
      'Hersteller/Importeur/Bevollmächtigten angeben',
    ],
    affectedProducts: ['Spielzeug', 'Maschinen', 'Medizinprodukte', 'Bauprodukte', 'Persönliche Schutzausrüstung', 'Elektrogeräte', 'Druckgeräte', 'u.v.m.'],
    dppDeadlines: {},
  },
  {
    id: 'epr',
    name: 'EPR (Extended Producer Responsibility)',
    fullName: 'Erweiterte Herstellerverantwortung nach der Abfallrahmenrichtlinie',
    description: 'Finanzielle und organisatorische Verantwortung der Hersteller für das End-of-Life ihrer Produkte.',
    category: 'recycling',
    status: 'active',
    effectiveDate: '2008-11-19',
    applicationDate: '2008-12-12',
    keyRequirements: [
      'Registrierung bei nationalen EPR-Systemen',
      'Finanzierung der Sammlung und Verwertung',
      'Mengenmeldungen und Berichterstattung',
      'Öko-Modulation der Gebühren',
      'Verbraucherkommunikation',
    ],
    affectedProducts: ['Verpackungen', 'Elektrogeräte', 'Batterien', 'Fahrzeuge', 'Reifen', 'Textilien (ab 2025)'],
    dppDeadlines: {},
  },
  {
    id: 'energy-label',
    name: 'EU-Energielabel',
    fullName: 'Verordnung (EU) 2017/1369 zur Festlegung eines Rahmens für die Energieverbrauchskennzeichnung',
    description: 'Einheitliche Energieverbrauchskennzeichnung für energieverbrauchsrelevante Produkte. Skala A bis G.',
    category: 'energy',
    status: 'active',
    effectiveDate: '2017-08-01',
    applicationDate: '2021-03-01',
    keyRequirements: [
      'Energielabel am Point of Sale',
      'Produktdatenblatt erstellen',
      'Registrierung in EPREL-Datenbank',
      'QR-Code auf Label (verlinkt zu EPREL)',
      'Werbematerial mit Energieklasse',
    ],
    affectedProducts: ['Kühlschränke', 'Waschmaschinen', 'Geschirrspüler', 'TVs', 'Leuchtmittel', 'Klimageräte', 'Reifen'],
    dppDeadlines: {},
  },
  {
    id: 'packaging-ppwr',
    name: 'PPWR (Packaging and Packaging Waste Regulation)',
    fullName: 'Verordnung über Verpackungen und Verpackungsabfälle',
    description: 'Ersetzt die bestehende Verpackungsrichtlinie. Strenge Recycling- und Wiederverwendungsziele, Mindestgehalt an recyceltem Material.',
    category: 'environment',
    status: 'upcoming',
    effectiveDate: '2024-12-31',
    applicationDate: '2025-01-01',
    keyRequirements: [
      'Alle Verpackungen müssen recycelbar sein (2030)',
      'Mindestgehalt an recyceltem Kunststoff',
      'Beschränkung von Einwegverpackungen',
      'Pfandsysteme für Getränkeflaschen',
      'Wiederverwendungsziele für bestimmte Sektoren',
      'Harmonisierte Kennzeichnung',
    ],
    affectedProducts: ['Alle Verpackungen'],
    dppDeadlines: {},
  },
  {
    id: 'csrd',
    name: 'CSRD (Corporate Sustainability Reporting Directive)',
    fullName: 'Richtlinie (EU) 2022/2464 zur Nachhaltigkeitsberichterstattung von Unternehmen',
    description: 'Erweiterte Nachhaltigkeitsberichtspflichten für große und börsennotierte Unternehmen nach European Sustainability Reporting Standards (ESRS).',
    category: 'environment',
    status: 'active',
    effectiveDate: '2023-01-05',
    applicationDate: '2024-01-01',
    keyRequirements: [
      'Berichterstattung nach ESRS',
      'Doppelte Wesentlichkeit (Double Materiality)',
      'Externe Prüfung des Nachhaltigkeitsberichts',
      'Digitales Tagging (XBRL/ESEF)',
      'Integration in Lagebericht',
    ],
    affectedProducts: ['Nicht produktspezifisch - Unternehmensebene'],
    dppDeadlines: {},
  },
  {
    id: 'csddd',
    name: 'CSDDD (Corporate Sustainability Due Diligence Directive)',
    fullName: 'Richtlinie über Sorgfaltspflichten von Unternehmen im Hinblick auf Nachhaltigkeit',
    description: 'Sorgfaltspflichten bezüglich Menschenrechte und Umwelt in der gesamten Wertschöpfungskette.',
    category: 'environment',
    status: 'upcoming',
    effectiveDate: '2024-07-25',
    applicationDate: '2027-07-26',
    keyRequirements: [
      'Identifizierung negativer Auswirkungen',
      'Prävention und Minderung von Schäden',
      'Beschwerdemechanismus einrichten',
      'Überwachung der Wirksamkeit',
      'Öffentliche Berichterstattung',
      'Klimaübergangsplan',
    ],
    affectedProducts: ['Nicht produktspezifisch - Unternehmensebene'],
    dppDeadlines: {},
  },
  {
    id: 'deforestation',
    name: 'EUDR (EU Deforestation Regulation)',
    fullName: 'Verordnung (EU) 2023/1115 über entwaldungsfreie Produkte',
    description: 'Verbot des Inverkehrbringens von Produkten, die mit Entwaldung oder Waldschädigung verbunden sind.',
    category: 'environment',
    status: 'upcoming',
    effectiveDate: '2023-06-29',
    applicationDate: '2024-12-30',
    keyRequirements: [
      'Due-Diligence-Erklärung vor dem Inverkehrbringen',
      'Geolokalisierung der Produktionsstandorte',
      'Nachweis der Entwaldungsfreiheit',
      'Rückverfolgbarkeit in der Lieferkette',
      'Risikobeurteilung und -minderung',
    ],
    affectedProducts: ['Rinder', 'Kakao', 'Kaffee', 'Palmöl', 'Soja', 'Holz', 'Kautschuk', 'und deren Folgeprodukte'],
    dppDeadlines: {},
  },
];

// ============================================
// NATIONALE REGULIERUNGEN
// ============================================

const nationalRegulations = [
  // Deutschland
  {
    id: 'de-elekrog',
    country_code: 'DE',
    name: 'ElektroG (Elektro- und Elektronikgerätegesetz)',
    description: 'Umsetzung der WEEE-Richtlinie. Registrierungspflicht bei stiftung ear, Rücknahmepflichten, Kennzeichnungspflichten.',
    category: 'Recycling',
    mandatory: true,
    effectiveDate: '2005-03-23',
    authority: 'stiftung ear / UBA',
    penalties: 'Bis zu 100.000 € Bußgeld',
    products: ['Elektronik', 'Elektrogeräte', 'IT-Equipment', 'Beleuchtung'],
  },
  {
    id: 'de-battg',
    country_code: 'DE',
    name: 'BattG (Batteriegesetz)',
    description: 'Rücknahme und Entsorgung von Batterien. Registrierung bei stiftung ear, Kennzeichnungspflichten, Mengenmeldungen.',
    category: 'Recycling',
    mandatory: true,
    effectiveDate: '2009-06-01',
    authority: 'stiftung ear / UBA',
    penalties: 'Bis zu 100.000 € Bußgeld',
    products: ['Batterien', 'Akkumulatoren', 'Knopfzellen'],
  },
  {
    id: 'de-verpackg',
    country_code: 'DE',
    name: 'VerpackG (Verpackungsgesetz)',
    description: 'Systembeteiligungspflicht für Verkaufsverpackungen. Registrierung bei LUCID, Mengenmeldungen, Recyclingquoten.',
    category: 'Verpackung',
    mandatory: true,
    effectiveDate: '2019-01-01',
    authority: 'Zentrale Stelle Verpackungsregister',
    penalties: 'Bis zu 200.000 € Bußgeld, Vertriebsverbot',
    products: ['Alle verpackten Produkte'],
  },
  {
    id: 'de-prodsg',
    country_code: 'DE',
    name: 'ProdSG (Produktsicherheitsgesetz)',
    description: 'Allgemeine Produktsicherheit, GS-Zeichen, Marktüberwachung. CE-Kennzeichnung für bestimmte Produktgruppen.',
    category: 'Sicherheit',
    mandatory: true,
    effectiveDate: '2011-12-01',
    authority: 'BAuA / Marktüberwachungsbehörden',
    penalties: 'Bis zu 100.000 € Bußgeld, Produktrückruf',
    products: ['Verbraucherprodukte', 'Spielzeug', 'Maschinen'],
  },
  {
    id: 'de-chemg',
    country_code: 'DE',
    name: 'ChemG (Chemikaliengesetz)',
    description: 'Nationale Umsetzung von REACH und CLP. Meldepflichten, Sicherheitsdatenblätter, Kennzeichnung.',
    category: 'Chemie',
    mandatory: true,
    effectiveDate: '2008-06-01',
    authority: 'BAuA / BfR',
    penalties: 'Bis zu 50.000 € Bußgeld',
    products: ['Chemikalien', 'Gemische', 'Produkte mit gefährlichen Stoffen'],
  },
  {
    id: 'de-gpsg',
    country_code: 'DE',
    name: 'GPSG (Geräte- und Produktsicherheitsgesetz)',
    description: 'Anforderungen an technische Arbeitsmittel und Verbraucherprodukte.',
    category: 'Sicherheit',
    mandatory: true,
    effectiveDate: '2004-05-01',
    authority: 'BAuA',
    penalties: 'Bis zu 30.000 € Bußgeld',
    products: ['Technische Arbeitsmittel', 'Verbraucherprodukte'],
  },
  {
    id: 'de-energievbrkg',
    country_code: 'DE',
    name: 'EnVKG (Energieverbrauchskennzeichnungsgesetz)',
    description: 'Umsetzung der EU-Energielabel-Verordnung. Pflicht zur Angabe des Energieverbrauchs.',
    category: 'Energie',
    mandatory: true,
    effectiveDate: '2012-05-01',
    authority: 'BAM / Marktüberwachung',
    penalties: 'Bis zu 50.000 € Bußgeld',
    products: ['Haushaltsgeräte', 'Leuchtmittel', 'Elektronik'],
  },
  {
    id: 'de-emvg',
    country_code: 'DE',
    name: 'EMVG (EMV-Gesetz)',
    description: 'Elektromagnetische Verträglichkeit von Geräten. CE-Kennzeichnung, Konformitätserklärung.',
    category: 'Sicherheit',
    mandatory: true,
    effectiveDate: '2016-12-22',
    authority: 'Bundesnetzagentur',
    penalties: 'Bis zu 100.000 € Bußgeld',
    products: ['Elektrische Geräte', 'Elektronik'],
  },
  // Frankreich
  {
    id: 'fr-agec',
    country_code: 'FR',
    name: 'Loi AGEC (Anti-Gaspillage pour une Économie Circulaire)',
    description: 'Umfassendes Anti-Verschwendungsgesetz mit Reparierbarkeitsindex, Ersatzteilverfügbarkeit, Verbot der Vernichtung unverkaufter Waren.',
    category: 'Nachhaltigkeit',
    mandatory: true,
    effectiveDate: '2020-02-10',
    authority: 'ADEME / DGCCRF',
    penalties: 'Bis zu 15.000 € pro Verstoß',
    products: ['Elektronik', 'Textilien', 'Möbel', 'Spielzeug'],
  },
  {
    id: 'fr-rep',
    country_code: 'FR',
    name: 'REP (Responsabilité Élargie du Producteur)',
    description: 'Erweiterte Herstellerverantwortung für 21+ Produktkategorien. Registrierung bei eco-organismes.',
    category: 'Recycling',
    mandatory: true,
    effectiveDate: '2022-01-01',
    authority: 'ADEME',
    penalties: 'Bis zu 200.000 € Bußgeld',
    products: ['Verpackungen', 'Elektronik', 'Textilien', 'Möbel', 'Spielzeug', 'Sportartikel'],
  },
  {
    id: 'fr-indice-reparabilite',
    country_code: 'FR',
    name: 'Indice de Réparabilité (Reparierbarkeitsindex)',
    description: 'Pflicht zur Anzeige des Reparierbarkeitsindex (0-10) am Point of Sale. Kriterien: Dokumentation, Demontage, Ersatzteile, Preis, Spezifische Kriterien.',
    category: 'Nachhaltigkeit',
    mandatory: true,
    effectiveDate: '2021-01-01',
    authority: 'DGCCRF',
    penalties: 'Bis zu 15.000 € pro Produkt',
    products: ['Smartphones', 'Laptops', 'TVs', 'Waschmaschinen', 'Rasenmäher', 'Staubsauger', 'Geschirrspüler', 'Hochdruckreiniger'],
  },
  {
    id: 'fr-triman',
    country_code: 'FR',
    name: 'Triman (Recyclage-Symbol)',
    description: 'Pflicht-Symbol für recycelbare Produkte und Verpackungen. Muss auf Produkt oder Verpackung sichtbar sein.',
    category: 'Kennzeichnung',
    mandatory: true,
    effectiveDate: '2015-01-01',
    authority: 'ADEME',
    penalties: 'Bis zu 7.500 € Bußgeld',
    products: ['Alle recycelbaren Produkte und Verpackungen'],
  },
  {
    id: 'fr-info-tri',
    country_code: 'FR',
    name: 'Info-tri (Sortierhinweise)',
    description: 'Detaillierte Entsorgungshinweise für Verbraucher. Muss ab 2022 auf allen Verpackungen erscheinen.',
    category: 'Kennzeichnung',
    mandatory: true,
    effectiveDate: '2022-01-01',
    authority: 'CITEO',
    penalties: 'Bis zu 7.500 € Bußgeld',
    products: ['Alle verpackten Produkte'],
  },
  {
    id: 'fr-unique-identifier',
    country_code: 'FR',
    name: 'Identifiant Unique (Unique Identifier)',
    description: 'Eindeutiger Identifikator für Produkte unter REP. Ermöglicht Rückverfolgbarkeit.',
    category: 'Kennzeichnung',
    mandatory: true,
    effectiveDate: '2023-01-01',
    authority: 'ADEME',
    penalties: 'Teil der REP-Sanktionen',
    products: ['Alle REP-pflichtigen Produkte'],
  },
  {
    id: 'fr-indice-durabilite',
    country_code: 'FR',
    name: 'Indice de Durabilité (Haltbarkeitsindex)',
    description: 'Erweitert den Reparierbarkeitsindex um Zuverlässigkeit und Robustheit. Ersetzt ab 2025 den Reparierbarkeitsindex.',
    category: 'Nachhaltigkeit',
    mandatory: true,
    effectiveDate: '2025-01-01',
    authority: 'DGCCRF',
    penalties: 'Bis zu 15.000 € pro Produkt',
    products: ['Elektronik', 'Haushaltsgeräte'],
  },
  // Österreich
  {
    id: 'at-eag',
    country_code: 'AT',
    name: 'EAG-VO (Elektroaltgeräteverordnung)',
    description: 'Sammlung und Verwertung von Elektroaltgeräten. Registrierung bei ERA.',
    category: 'Recycling',
    mandatory: true,
    effectiveDate: '2005-08-13',
    authority: 'BMK / ERA',
    penalties: 'Bis zu 42.000 € Bußgeld',
    products: ['Elektrogeräte', 'Elektronik'],
  },
  {
    id: 'at-verpackvo',
    country_code: 'AT',
    name: 'VerpackVO (Verpackungsverordnung)',
    description: 'Sammlung und Verwertung von Verpackungen. Lizenzierung bei ARA oder anderen Systemen.',
    category: 'Verpackung',
    mandatory: true,
    effectiveDate: '1996-10-01',
    authority: 'BMK',
    penalties: 'Bis zu 36.000 € Bußgeld',
    products: ['Alle verpackten Produkte'],
  },
  {
    id: 'at-battvo',
    country_code: 'AT',
    name: 'Batterieverordnung',
    description: 'Sammlung und Verwertung von Batterien. Registrierung und Mengenmeldungen.',
    category: 'Recycling',
    mandatory: true,
    effectiveDate: '2008-12-01',
    authority: 'BMK',
    penalties: 'Bis zu 36.000 € Bußgeld',
    products: ['Batterien', 'Akkumulatoren'],
  },
  {
    id: 'at-chemg',
    country_code: 'AT',
    name: 'ChemG (Chemikaliengesetz)',
    description: 'Österreichische Umsetzung von REACH und CLP.',
    category: 'Chemie',
    mandatory: true,
    effectiveDate: '2008-06-01',
    authority: 'AGES',
    penalties: 'Bis zu 36.000 € Bußgeld',
    products: ['Chemikalien', 'Gemische'],
  },
];

// ============================================
// PIKTOGRAMME
// ============================================

const pictograms = [
  // CE und Sicherheit
  {
    id: 'ce',
    symbol: 'CE',
    name: 'CE-Kennzeichnung',
    description: 'Zeigt EU-Konformität an. Erforderlich für viele Produktkategorien vor dem Inverkehrbringen.',
    mandatory: true,
    countries: ['EU'],
    category: 'safety',
    dimensions: 'Mind. 5mm Höhe, Proportionen gemäß Anhang II Beschluss 768/2008/EG',
    placement: 'Auf Produkt, Verpackung oder Dokumenten',
  },
  {
    id: 'gs',
    symbol: 'GS',
    name: 'GS-Zeichen (Geprüfte Sicherheit)',
    description: 'Freiwilliges deutsches Sicherheitszeichen. Nachweis der Prüfung durch eine zugelassene Stelle.',
    mandatory: false,
    countries: ['DE'],
    category: 'safety',
    dimensions: 'Keine Mindestgröße, aber erkennbar',
    placement: 'Auf Produkt',
  },
  // Recycling und Entsorgung
  {
    id: 'weee',
    symbol: '🗑️❌',
    name: 'WEEE-Symbol (Durchgestrichene Mülltonne)',
    description: 'Elektro- und Elektronikgeräte dürfen nicht im Hausmüll entsorgt werden. Getrennte Sammlung erforderlich.',
    mandatory: true,
    countries: ['EU'],
    category: 'recycling',
    dimensions: 'Mind. 7mm x 10mm, gemäß EN 50419',
    placement: 'Auf Produkt oder Etikett, dauerhaft',
  },
  {
    id: 'triman',
    symbol: '🔄',
    name: 'Triman',
    description: 'Französisches Recycling-Symbol. Zeigt an, dass das Produkt einem Sammelsystem unterliegt.',
    mandatory: true,
    countries: ['FR'],
    category: 'recycling',
    dimensions: 'Mind. 6mm bei bedruckter Fläche',
    placement: 'Auf Produkt oder Verpackung',
  },
  {
    id: 'info-tri',
    symbol: '🗂️',
    name: 'Info-tri',
    description: 'Französische Sortieranleitung. Gibt an, wie jeder Teil der Verpackung entsorgt werden soll.',
    mandatory: true,
    countries: ['FR'],
    category: 'recycling',
    dimensions: 'Lesbar',
    placement: 'Auf Verpackung',
  },
  {
    id: 'green-dot',
    symbol: '♻️',
    name: 'Grüner Punkt',
    description: 'Zeigt die Teilnahme an einem Dualen System für Verpackungsrecycling. In manchen Ländern noch erforderlich.',
    mandatory: false,
    countries: ['DE', 'AT', 'ES', 'PT'],
    category: 'recycling',
    dimensions: 'Keine Mindestgröße',
    placement: 'Auf Verpackung',
  },
  {
    id: 'mobius-loop',
    symbol: '♲',
    name: 'Möbius-Schleife (Recycling-Symbol)',
    description: 'Zeigt an, dass das Material recycelbar ist oder aus recyceltem Material besteht. Mit Prozentangabe: Recyclinganteil.',
    mandatory: false,
    countries: ['EU'],
    category: 'recycling',
    dimensions: 'Keine Mindestgröße',
    placement: 'Auf Produkt oder Verpackung',
  },
  // Reparierbarkeit und Haltbarkeit
  {
    id: 'repairability-fr',
    symbol: '🔧',
    name: 'Indice de Réparabilité',
    description: 'Französischer Reparierbarkeitsindex (0-10). Farbe von Rot (schlecht) bis Grün (gut).',
    mandatory: true,
    countries: ['FR'],
    category: 'durability',
    dimensions: 'Gemäß Décret n° 2020-1757',
    placement: 'Am Point of Sale, auf Verpackung oder Produkt',
  },
  {
    id: 'durability-fr',
    symbol: '⏱️',
    name: 'Indice de Durabilité',
    description: 'Französischer Haltbarkeitsindex (ab 2025). Erweitert den Reparierbarkeitsindex um Zuverlässigkeit.',
    mandatory: true,
    countries: ['FR'],
    category: 'durability',
    dimensions: 'Gemäß kommender Verordnung',
    placement: 'Am Point of Sale, auf Verpackung oder Produkt',
  },
  // Energie
  {
    id: 'energy-label',
    symbol: '⚡',
    name: 'EU-Energielabel',
    description: 'Zeigt Energieeffizienzklasse (A-G) und weitere Produkteigenschaften. QR-Code verlinkt zu EPREL.',
    mandatory: true,
    countries: ['EU'],
    category: 'energy',
    dimensions: 'Standardgröße gemäß produktspezifischer Verordnung',
    placement: 'Am Point of Sale',
  },
  {
    id: 'ecodesign',
    symbol: '🌿',
    name: 'EU-Ökodesign',
    description: 'Zeigt Konformität mit Ökodesign-Anforderungen für energieverbrauchsrelevante Produkte.',
    mandatory: false,
    countries: ['EU'],
    category: 'energy',
    dimensions: 'Keine Mindestgröße',
    placement: 'Optional auf Produkt',
  },
  // Batterien
  {
    id: 'battery-collection',
    symbol: '🔋❌',
    name: 'Batteriesammlung',
    description: 'Durchgestrichene Mülltonne für Batterien. Zeigt getrennte Sammlung an.',
    mandatory: true,
    countries: ['EU'],
    category: 'recycling',
    dimensions: 'Mind. 3% der Oberfläche, max. 5cm x 5cm',
    placement: 'Auf Batterie oder Verpackung',
  },
  {
    id: 'battery-chemistry',
    symbol: 'Pb/Cd/Hg',
    name: 'Batterie-Chemie-Symbol',
    description: 'Chemische Symbole für Blei, Cadmium oder Quecksilber wenn >Grenzwert.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Unter dem Symbol der durchgestrichenen Mülltonne',
    placement: 'Auf Batterie',
  },
  // Chemie und Gefahrstoffe
  {
    id: 'ghs-explosive',
    symbol: '💥',
    name: 'GHS01 - Explosiv',
    description: 'Explodierende Bombe. Für explosive Stoffe und Gemische.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-flammable',
    symbol: '🔥',
    name: 'GHS02 - Entzündbar',
    description: 'Flamme. Für entzündbare Gase, Aerosole, Flüssigkeiten, Feststoffe.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-oxidizing',
    symbol: '⭕🔥',
    name: 'GHS03 - Oxidierend',
    description: 'Flamme über Kreis. Für oxidierende Gase, Flüssigkeiten, Feststoffe.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-gas',
    symbol: '🧪',
    name: 'GHS04 - Gasflasche',
    description: 'Gasflasche. Für verdichtete, verflüssigte, gelöste Gase.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-corrosive',
    symbol: '⚗️',
    name: 'GHS05 - Ätzend',
    description: 'Ätzwirkung. Für hautätzende und augenschädigende Stoffe.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-toxic',
    symbol: '☠️',
    name: 'GHS06 - Giftig',
    description: 'Totenkopf mit Knochen. Für akut toxische Stoffe.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-harmful',
    symbol: '⚠️',
    name: 'GHS07 - Reizend',
    description: 'Ausrufezeichen. Für reizende, sensibilisierende, narkotische Stoffe.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-health',
    symbol: '⚕️',
    name: 'GHS08 - Gesundheitsgefahr',
    description: 'Gesundheitsgefahr. Für CMR-Stoffe, STOT, Aspirationsgefahr.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
  {
    id: 'ghs-environment',
    symbol: '🌳',
    name: 'GHS09 - Umweltgefährlich',
    description: 'Umwelt. Für gewässergefährdende Stoffe.',
    mandatory: true,
    countries: ['EU'],
    category: 'chemicals',
    dimensions: 'Gemäß CLP-Verordnung',
    placement: 'Auf Verpackung',
  },
];

// ============================================
// RECYCLING-CODES
// ============================================

const recyclingCodes = [
  { code: '1', symbol: '♳', name: 'PET', fullName: 'Polyethylenterephthalat', examples: 'Getränkeflaschen, Lebensmittelverpackungen', recyclable: true },
  { code: '2', symbol: '♴', name: 'HDPE', fullName: 'Polyethylen hoher Dichte', examples: 'Milchflaschen, Reinigungsmittel', recyclable: true },
  { code: '3', symbol: '♵', name: 'PVC', fullName: 'Polyvinylchlorid', examples: 'Rohre, Fensterrahmen, Kabel', recyclable: false },
  { code: '4', symbol: '♶', name: 'LDPE', fullName: 'Polyethylen niedriger Dichte', examples: 'Plastiktüten, Folien', recyclable: true },
  { code: '5', symbol: '♷', name: 'PP', fullName: 'Polypropylen', examples: 'Joghurtbecher, Verschlüsse', recyclable: true },
  { code: '6', symbol: '♸', name: 'PS', fullName: 'Polystyrol', examples: 'Styropor, Einweggeschirr', recyclable: false },
  { code: '7', symbol: '♹', name: 'O', fullName: 'Andere Kunststoffe', examples: 'PC, PA, ABS, etc.', recyclable: false },
  { code: '20', symbol: '♺', name: 'PAP', fullName: 'Wellpappe', examples: 'Kartons', recyclable: true },
  { code: '21', symbol: '♺', name: 'PAP', fullName: 'Sonstige Pappe', examples: 'Faltschachteln', recyclable: true },
  { code: '22', symbol: '♺', name: 'PAP', fullName: 'Papier', examples: 'Zeitungen, Magazine', recyclable: true },
  { code: '40', symbol: '♻', name: 'FE', fullName: 'Stahl', examples: 'Konservendosen', recyclable: true },
  { code: '41', symbol: '♻', name: 'ALU', fullName: 'Aluminium', examples: 'Getränkedosen', recyclable: true },
  { code: '70', symbol: '♻', name: 'GL', fullName: 'Farbloses Glas', examples: 'Flaschen, Gläser', recyclable: true },
  { code: '71', symbol: '♻', name: 'GL', fullName: 'Grünes Glas', examples: 'Weinflaschen', recyclable: true },
  { code: '72', symbol: '♻', name: 'GL', fullName: 'Braunes Glas', examples: 'Bierflaschen', recyclable: true },
];

// ============================================
// NEWS
// ============================================

const news = [
  {
    id: '1',
    title: 'ESPR: Delegierte Rechtsakte für erste Produktkategorien erwartet',
    summary: 'Die EU-Kommission arbeitet an den ersten delegierten Rechtsakten unter der ESPR. Textilien und Eisen/Stahl werden voraussichtlich die ersten sein.',
    content: 'Die Europäische Kommission hat angekündigt, dass die ersten produktspezifischen Anforderungen unter der neuen Ökodesign-Verordnung für nachhaltige Produkte (ESPR) im Laufe des Jahres 2025 verabschiedet werden. Textilien und Eisen/Stahl sind als Pilotkategorien vorgesehen, gefolgt von Möbeln, Reifen und Waschmitteln.',
    category: 'regulation',
    countries: ['EU'],
    publishedAt: '2025-01-15',
    effectiveDate: '2027-01-01',
    priority: 'high',
    tags: ['ESPR', 'DPP', 'Textilien', 'Ökodesign'],
  },
  {
    id: '2',
    title: 'Batterie-DPP: Technische Standards veröffentlicht',
    summary: 'Die EU hat die technischen Spezifikationen für den Batterie-Produktpass veröffentlicht. QR-Code-Anforderungen und Datenformate sind jetzt definiert.',
    content: 'Nach langer Konsultationsphase hat die EU-Kommission die technischen Standards für den digitalen Batteriepass veröffentlicht. Diese definieren die Mindestanforderungen an QR-Codes, Datenformate (JSON-LD), und die verpflichtenden Datenfelder. Hersteller müssen ab Februar 2027 für Batterien >2kWh einen digitalen Pass bereitstellen.',
    category: 'deadline',
    countries: ['EU'],
    publishedAt: '2025-01-10',
    effectiveDate: '2027-02-18',
    priority: 'high',
    tags: ['Batterie', 'DPP', 'QR-Code', 'Standards'],
  },
  {
    id: '3',
    title: 'Frankreich: Reparierbarkeitsindex wird zum Haltbarkeitsindex',
    summary: 'Ab 2025 wird der französische Reparierbarkeitsindex durch den umfassenderen Haltbarkeitsindex ersetzt.',
    content: 'Frankreich erweitert sein Pionier-System der Produktbewertung. Der neue "Indice de Durabilité" (Haltbarkeitsindex) integriert neben der Reparierbarkeit auch Kriterien wie Zuverlässigkeit und Robustheit. Erste Produktkategorien sind Smartphones, Laptops, Fernseher und Waschmaschinen.',
    category: 'update',
    countries: ['FR'],
    publishedAt: '2025-01-05',
    effectiveDate: '2025-01-01',
    priority: 'medium',
    tags: ['Frankreich', 'Reparierbarkeit', 'Haltbarkeit', 'AGEC'],
  },
  {
    id: '4',
    title: 'SCIP-Datenbank: Über 100 Millionen Meldungen erreicht',
    summary: 'Die ECHA-Datenbank für SVHC-haltige Erzeugnisse wächst weiter. Neue Einreichungsanforderungen ab 2025.',
    content: 'Die SCIP-Datenbank (Substances of Concern In articles as such or in complex objects/Products) hat einen Meilenstein erreicht. Die ECHA hat neue Leitlinien veröffentlicht, die die Anforderungen an die Datenqualität verschärfen. Unternehmen müssen ihre bestehenden Einträge überprüfen und aktualisieren.',
    category: 'warning',
    countries: ['EU'],
    publishedAt: '2025-01-02',
    effectiveDate: '2025-03-01',
    priority: 'medium',
    tags: ['REACH', 'SVHC', 'SCIP', 'ECHA'],
  },
  {
    id: '5',
    title: 'Deutschland: stiftung ear aktualisiert Mengenmeldeverfahren',
    summary: 'Neue elektronische Schnittstellen für die Mengenmeldung bei der stiftung ear ab Q2 2025.',
    content: 'Die stiftung elektro-altgeräte register führt ein neues API-basiertes Meldesystem ein. Hersteller und Bevollmächtigte müssen ihre Systeme bis Juni 2025 anpassen. Das alte XML-Format wird ab 2026 nicht mehr unterstützt.',
    category: 'update',
    countries: ['DE'],
    publishedAt: '2024-12-20',
    effectiveDate: '2025-06-01',
    priority: 'medium',
    tags: ['ElektroG', 'stiftung ear', 'API', 'Mengenmeldung'],
  },
  {
    id: '6',
    title: 'PPWR: Finale Abstimmung im EU-Parlament erfolgt',
    summary: 'Die neue Verpackungsverordnung wurde angenommen. Strenge Recycling- und Wiederverwendungsziele kommen.',
    content: 'Das EU-Parlament hat die Verordnung über Verpackungen und Verpackungsabfälle (PPWR) angenommen. Wichtige Punkte: Alle Verpackungen müssen bis 2030 recycelbar sein, Mindestgehalt an recyceltem Kunststoff, Beschränkungen für Einwegverpackungen, harmonisierte Kennzeichnung EU-weit.',
    category: 'regulation',
    countries: ['EU'],
    publishedAt: '2024-12-15',
    effectiveDate: '2025-01-01',
    priority: 'high',
    tags: ['PPWR', 'Verpackung', 'Recycling', 'Kreislaufwirtschaft'],
  },
  {
    id: '7',
    title: 'Textil-DPP: Erste Pilotprojekte gestartet',
    summary: 'Mehrere große Modemarken testen den digitalen Produktpass für Textilien in Pilotprojekten.',
    content: 'Im Vorgriff auf die kommenden ESPR-Anforderungen haben führende Textilunternehmen Pilotprojekte für den digitalen Produktpass gestartet. Die Projekte testen verschiedene Ansätze für QR-Codes, NFC-Tags und die Integration von Lieferkettendaten.',
    category: 'update',
    countries: ['EU'],
    publishedAt: '2024-12-10',
    effectiveDate: '2027-12-31',
    priority: 'low',
    tags: ['Textilien', 'DPP', 'Pilotprojekt', 'Mode'],
  },
  {
    id: '8',
    title: 'EUDR: Übergangsfrist verlängert',
    summary: 'Die EU hat eine 12-monatige Verschiebung der Anwendung der Entwaldungsverordnung angekündigt.',
    content: 'Aufgrund von Bedenken bezüglich der Umsetzungsbereitschaft hat die EU-Kommission vorgeschlagen, die Anwendung der EUDR um 12 Monate zu verschieben. Große Unternehmen müssen nun ab Dezember 2025 statt Dezember 2024 compliant sein.',
    category: 'deadline',
    countries: ['EU'],
    publishedAt: '2024-12-01',
    effectiveDate: '2025-12-30',
    priority: 'high',
    tags: ['EUDR', 'Entwaldung', 'Due Diligence', 'Verschiebung'],
  },
  {
    id: '9',
    title: 'Österreich: Neues EPR-System für Textilien ab 2025',
    summary: 'Österreich führt ein erweitertes Herstellerverantwortungssystem für Textilien ein.',
    content: 'Das Bundesministerium für Klimaschutz hat die Einführung eines EPR-Systems für Textilien und Schuhe angekündigt. Hersteller und Importeure müssen sich registrieren und Entsorgungsgebühren zahlen. Das System soll bis Mitte 2025 operativ sein.',
    category: 'regulation',
    countries: ['AT'],
    publishedAt: '2024-11-25',
    effectiveDate: '2025-07-01',
    priority: 'medium',
    tags: ['Österreich', 'EPR', 'Textilien', 'Kreislaufwirtschaft'],
  },
  {
    id: '10',
    title: 'REACH: Neue SVHC auf der Kandidatenliste',
    summary: 'ECHA hat 5 neue besonders besorgniserregende Stoffe auf die Kandidatenliste gesetzt.',
    content: 'Die Europäische Chemikalienagentur hat die Kandidatenliste um 5 neue SVHCs erweitert. Unternehmen müssen prüfen, ob ihre Produkte diese Stoffe enthalten und ggf. SCIP-Meldungen aktualisieren sowie Kunden informieren.',
    category: 'warning',
    countries: ['EU'],
    publishedAt: '2024-11-20',
    effectiveDate: '2025-01-15',
    priority: 'high',
    tags: ['REACH', 'SVHC', 'Chemikalien', 'ECHA'],
  },
  {
    id: '11',
    title: 'Italien: Neue Verpackungskennzeichnung tritt in Kraft',
    summary: 'Italiens Decreto 116/2020 verlangt detaillierte Entsorgungshinweise auf allen Verpackungen.',
    content: 'Nach mehrfacher Verschiebung ist die italienische Verpackungskennzeichnungspflicht nun verbindlich. Alle Verpackungen müssen Materialcodes (gemäß Entscheidung 129/97/CE) und Entsorgungshinweise für Verbraucher tragen.',
    category: 'deadline',
    countries: ['IT'],
    publishedAt: '2024-11-15',
    effectiveDate: '2024-01-01',
    priority: 'medium',
    tags: ['Italien', 'Verpackung', 'Kennzeichnung', 'CONAI'],
  },
  {
    id: '12',
    title: 'Niederlande: Circular Economy Implementation Programme 2025',
    summary: 'Die Niederlande veröffentlichen ihre aktualisierte Kreislaufwirtschaftsstrategie.',
    content: 'Das niederländische Programm sieht vor, dass die Niederlande bis 2050 vollständig zirkulär wirtschaften. Neue Maßnahmen betreffen insbesondere Kunststoffe, Textilien und Elektronik mit erhöhten Recyclingzielen und Produktdesign-Anforderungen.',
    category: 'regulation',
    countries: ['NL'],
    publishedAt: '2024-11-10',
    effectiveDate: '2025-01-01',
    priority: 'low',
    tags: ['Niederlande', 'Kreislaufwirtschaft', 'Nachhaltigkeit'],
  },
];

// ============================================
// DEMO-TENANT
// ============================================

const demoTenant = {
  id: 'demo',
  name: 'GreenStep GmbH',
  slug: 'greenstep',
  logo: '/logo.png',
  address: 'Nachhaltigkeitsstraße 42, 80331 München',
  country: 'DE',
  eori: 'DE123456789012345',
  vat: 'DE123456789',
  settings: {
    defaultLanguage: 'de',
    qrCodeStyle: 'branded',
  },
  plan: 'pro',
  createdAt: '2024-01-01T00:00:00Z',
};

// ============================================
// DEMO-DOKUMENTE
// ============================================

const demoDocuments = [
  {
    id: '1',
    tenant_id: 'demo',
    name: 'CE_Konformitaetserklarung_EcoSneaker.pdf',
    type: 'pdf',
    product_id: '1',
    category: 'Konformität',
    uploadedAt: '2024-06-10',
    validUntil: '2027-06-10',
    status: 'valid',
    size: '245 KB',
  },
  {
    id: '2',
    tenant_id: 'demo',
    name: 'OEKO-TEX_Zertifikat_100.pdf',
    type: 'pdf',
    product_id: '1',
    category: 'Zertifikat',
    uploadedAt: '2024-03-15',
    validUntil: '2025-06-30',
    status: 'expiring',
    size: '1.2 MB',
  },
  {
    id: '3',
    tenant_id: 'demo',
    name: 'EU_Ecolabel_Certificate.pdf',
    type: 'pdf',
    product_id: '1',
    category: 'Zertifikat',
    uploadedAt: '2024-01-20',
    validUntil: '2026-12-31',
    status: 'valid',
    size: '890 KB',
  },
  {
    id: '4',
    tenant_id: 'demo',
    name: 'LCA_Report_2024.pdf',
    type: 'pdf',
    product_id: '2',
    category: 'Bericht',
    uploadedAt: '2024-08-15',
    validUntil: null,
    status: 'valid',
    size: '3.4 MB',
  },
  {
    id: '5',
    tenant_id: 'demo',
    name: 'Materialdatenblatt_PET.pdf',
    type: 'pdf',
    product_id: '1',
    category: 'Datenblatt',
    uploadedAt: '2024-05-20',
    validUntil: null,
    status: 'valid',
    size: '156 KB',
  },
  {
    id: '6',
    tenant_id: 'demo',
    name: 'Testbericht_TUV.pdf',
    type: 'pdf',
    product_id: '2',
    category: 'Testbericht',
    uploadedAt: '2024-07-30',
    validUntil: '2025-01-15',
    status: 'expired',
    size: '2.1 MB',
  },
];

// ============================================
// EXPORT FUNKTIONEN
// ============================================

function writeJson(filename: string, data: unknown): void {
  const filepath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(filepath, JSON.stringify(data, null, 2), 'utf-8');
  console.log(`Exported: ${filename} (${Array.isArray(data) ? data.length : 1} entries)`);
}

function main(): void {
  console.log('=== DPP Manager Data Export ===\n');
  console.log(`Output directory: ${OUTPUT_DIR}\n`);

  // Master-Daten exportieren
  writeJson('categories.json', productCategories);
  writeJson('countries.json', countries);
  writeJson('regulations_eu.json', euRegulations);
  writeJson('regulations_national.json', nationalRegulations);
  writeJson('pictograms.json', pictograms);
  writeJson('recycling_codes.json', recyclingCodes);
  writeJson('news.json', news);

  // Tenant-Daten exportieren
  writeJson('tenants.json', [demoTenant]);
  writeJson('documents.json', demoDocuments);

  console.log('\n=== Export completed ===');
  console.log('\nNext steps:');
  console.log('1. Create tables in NoCodeBackend');
  console.log('2. Import JSON files via NoCodeBackend API or Admin UI');
  console.log('3. Update frontend pages to use API instead of hardcoded data');
}

main();
