/**
 * GENERATED by scripts/build-first-run-assets.mjs — do not edit by hand.
 *
 * Each entry is a 24x42 WebP inlined as a data URI, painted as the slide's
 * background-image while the full-size backdrop decodes. Upscaling 24px to full
 * screen IS the blur, for free, on the GPU — no filter: blur() needed.
 *
 * FirstRunAsset is a string-literal union, so a typo'd or renamed slug becomes a
 * compile error in `tsc --noEmit`, which already gates the build.
 */
export type FirstRunAsset = 'journey-scan' | 'journey-passport' | 'journey-compliance' | 'journey-returns' | 'journey-suppliers' | 'journey-portal' | 'journey-insight' | 'hub-requirements' | 'hub-checklists' | 'hub-qr' | 'hub-regulations' | 'hub-lexicon' | 'hub-tips';

export const LQIP: Record<FirstRunAsset, string> = {
  'journey-scan':
    'data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBQCdASoYACoAPu1qq0+ppiOiKrgMATAdiWUAxvRF7WND9k+CAJBTnH3qKhgh9MUc39SRKAD++b1GM7wCcm1ch7W76HJF6tdTscnmyWwGiNERZqV+vNWUvjhgI72OT1NggvziLLFT2crrWsXflwBfTYV1IZS5KGZrUnsuWSBZb/j4jgIdploi3yDIP12TJC/PiBYeLosQAAAA',
  'journey-passport':
    'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoYACoAPu1urlIppiQipWsxMB2JZQDMWC5tZZylw5YeLP0oLCZ7NvCAAP74R+x4csoWpnSEify6LD8U8ph9FnkMqXN/TY7CymGK2H20EDsOwzauG6WnKkD0Uxfh0J/h+x5nt7/I1XwqSVnjwXwUmkXzivJKWYMyrlTZl6CXV1lqQ5AA',
  'journey-compliance':
    'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwBACdASoYACoAPu1urlIppiQipWsxMB2JZQAAfw/3mRAppzTG5dRVHU4vD0eXD4AA/vhIHSo7h8U3trB3s7fnv/3FZbNcwNq3JgG5/FBEHfXvTC2KsPe+BxbTJdPh4GJZNCdrhEAkQE+4dXqtcE87e1USPsaXGaOtp8qHCgR5E34IoQZ10SwAAAA=',
  'journey-returns':
    'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBQCdASoYACoAPu1srFEppiQiqrgKATAdiWUAzNA6fWYI4yS9Y8ncx2AYYmhrcgELsNAAAP75CrLA5JlCsFdrvYua9H7K7eV+Dkrxtip5c9dSbPDBxla2/T+W1ZXsoXZp7YiYf8isvor7Aw5fWA3fl8NbqItiO6FMAYRYuZh8XmaGtpFJR5WGf8B1itsAAAA=',
  'journey-suppliers':
    'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwBACdASoYACoAPu1qrE+ppiSiKrgMATAdiWUAyFxRXaeQUHh42ErRPgzzwAD+9Mcx2TmT6umcrhdOv89jOY7nL2YefhVTRFtMBFHegBgdrFKWbvXnCP+jBziXxGgO1fgAAA==',
  'journey-portal':
    'data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAAAQBQCdASoYACoAPu1wrVMppiOipWmZMB2JZwDKAG1XjHIvqxKkJxNDpZ6s9PBg/EwAAP72o00EPGfSoVCfEngBPbQhEQ5XqCczvy+iL9yN+56m9hr+4GYVHoBMMGbTv+hbaXiI9GkyhT+jmeKnQND5ka5stoj/img3bimyohgWxzSTOldSCAJkIby5XUO2HsvXLmtNIdeVFDisPWI1e5shkmyZUhLq0gD5AAAA',
  'journey-insight':
    'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwBACdASoYACoAPu1orFApqqQmsBVYAVAdiWcAzfw15CIjKg27Ihbb7inZyDtAAP7xq4PIXJCG8/JX3OdfBDPLXVlcC786EmY6bIEqCeM9qcpE1QBotZ7d2XAAAA==',
  'hub-requirements':
    'data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBQCdASoYACoAPtVWo02oKSMiOrmYASAaiWUAyrRdboGlD3WoghKaTOwVx+FoeRXvyHowAP70bNATZ1Js1AcsA07EVchdAJGWgO+CHYPxzu6Jt3yMe4wHVvlvRWvSavwqPo0GOqGXp/q7QBf1VUiIb79VKYBjojc91wdG3LiEEMDCTA471rkghiPtx8cm943xKAAA',
  'hub-checklists':
    'data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwBQCdASoYACoAPu1ip04ppSMiNVQIATAdiWVdgFZAneZZzUMtf/ixv4WWt/w6KOyDmIhqZgAA/vGkeTJBKbpj3AVu7JhVy53I1Kg5Wq7wytxRNMgOiS58WlaT9vdRXYTfnBnArb3pSsUsk+4Ov7MbS83RjCVeRssiH1JVZHy9OqjZAj4itxt67rC+2dpj6JtS1SjIAbOpW9mxC1xQfxMCCHNL92rdQjLgtuDbgAA=',
  'hub-qr':
    'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBQCdASoYACoAPu1grU8ppSQmsBVaqTAdiWcAwvgubV8cKn7zl3Nyv+cOlXiiGCUS4yXBAoAA/vaOewB1l5yn4mZ7Zk0yG0qvldbm7PI+LOSbc0Px+PUc4DCxinLEytiIUh6VQxtLq0a5QxL5omECSzYNVD9o+tBvTac0QAAAAA==',
  'hub-regulations':
    'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwBACdASoYACoAPu1iqE2ppaOiMAgBMB2JZwDK8CHfF1c41nIhnltvaC0WgAD+8pnmI7oLWEp0t4s7sxJ6q3FsRfFXEnqyzzY2xF0T8Noaias02AiC0heNEFxGz9SSN5buGp5TKSP1CNyx1cAAAA==',
  'hub-lexicon':
    'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBQCdASoYACoAPu1iq1AppSOiqrgMATAdiWUAxkAir1FMayOtVAotODyWsdl1ThH+AAD+9CHKrUtZeiWHkXAjUZaIw0Ag0uU+BE2QXUYWYtR6jPfY/YY+VCw8XEqpMm375gH243jJP70k8XM0/iBG7bMuXuGQx7fK0U9yq+Q/bh5hPrIAAA==',
  'hub-tips':
    'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoYACoAPulip02pJaOiNVgIASAdCWUAyNRb952W9MxzD1JHw4AA/vFc2ySlBZk3g0M0qimfGypoG/rcb0+osWmkDQU0h3/irMu82j17HEqA8OVmbaEiIEL6/ccw8arN5Mt/tlL8KU+mECSy6HAZ/gAA',
};
